csiConfig:
  - clusterID: "f3d92a20-15cc-4820-a4d3-43894c625b8f"
    monitors:
      - "192.168.137.11:3300"
      - "192.168.137.12:3300"
      - "192.168.137.13:3300"
provisioner:
  replicaCount: 2
plugin:
  kubeletDir: /var/lib/kubelet
  nodeplugin:
    httpMetrics:
      containerPort: 8092
    nodeAffinity: {}
